name: myapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  provider: ^6.1.5
  awesome_notifications: ^0.10.1
  uuid: ^4.5.1
  firebase_auth: ^5.7.0
  google_sign_in: ^7.1.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  cloud_firestore: ^5.6.12
  permission_handler: ^12.0.1
  connectivity_plus: ^6.1.4
  firebase_crashlytics: ^4.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

